In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.utils import shuffle

In [2]:
UDP_flood= pd.read_csv('C:/Users/hp/Desktop/csv/UDP_flood.csv')
SYN_flood= pd.read_csv('C:/Users/hp/Desktop/csv/SYN_flood.csv')
ICMP_flood= pd.read_csv('C:/Users/hp/Desktop/csv/ICMP_flood.csv')

c:\Users\hp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
UDP_flood['Label'] = UDP_flood['Label'].replace({'No Label': 'DOS UDP '})
SYN_flood['Label'] = SYN_flood['Label'].replace({'No Label': 'DOS SYN '})
ICMP_flood['Label'] = ICMP_flood['Label'].replace({'No Label': 'DOS ICMP'})

In [4]:
DOS = pd.concat([SYN_flood, UDP_flood,ICMP_flood])

In [5]:
Normal_flood= pd.read_csv('C:/Users/hp/Desktop/csv/Normal_flood.csv')
Normal_flood['Label'] = Normal_flood['Label'].replace({'No Label': 'Normal'})

dataset = pd.concat([DOS,Normal_flood])
dataset = dataset.dropna()
dataset = shuffle(dataset)
dataset.columns.to_list()

dataset




,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1944,6,387.0,0.0,2.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.00000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,DOS ICMP
9330,6,90044004.0,2.0,4.0,2.0,1.0,1.0,1.0,1.000000,0.000000,...,0.0,14189.50000,774.281925,14737.0,13642.0,4.500000e+07,1.275621e+03,45000000.0,45000000.0,DOS UDP
2247,6,37051725.0,2.0,1.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.00000,0.000000,0.0,0.0,1.850000e+07,1.290000e+07,27600000.0,9431313.0,DOS SYN
16938,6,111985199.0,2.0,1.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.00000,0.000000,0.0,0.0,5.600000e+07,4.400000e+07,87100000.0,24900000.0,DOS SYN
15210,17,13247.0,0.0,2.0,0.0,172.0,0.0,0.0,0.000000,0.000000,...,0.0,0.00000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,17,65810851.0,10.0,14.0,852.0,646.0,557.0,29.0,85.200000,165.796260,...,0.0,63336.57143,119460.237700,332927.0,6618.0,9.337289e+06,4.609522e+06,15000000.0,5017653.0,DOS UDP
2973,17,25291868.0,25.0,27.0,2231.0,4501.0,503.0,31.0,89.240000,116.651290,...,0.0,489015.00000,454156.300800,810152.0,167878.0,1.140000e+07,4.275062e+05,11700000.0,11100000.0,Normal
2387,17,11273852.0,2.0,2.0,94.0,213.0,47.0,47.0,47.000000,0.000000,...,0.0,0.00000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,DOS ICMP
168,6,98143159.0,22.0,28.0,7775.0,4162.0,1150.0,0.0,353.409091,462.805591,...,0.0,144476.33330,131844.253900,284777.0,23143.0,3.260000e+07,2.150000e+07,45000000.0,7683483.0,DOS UDP


In [23]:
x= dataset[[ 
'RST Flag Cnt',    
'Pkt Len Max' , 
'Flow IAT Min' ,   
'Init Bwd Win Byts',   
'Flow IAT Max',   
'Bwd IAT Min',    
'Subflow Bwd Byts',   
'Fwd Pkts/s',    
'Flow IAT Mean',    
'Bwd IAT Tot',    
'Bwd Pkts/s',    
'Pkt Len Min',    
'Fwd Seg Size Avg',   
'Fwd IAT Min',    
'Bwd Header Len',    
'Fwd IAT Tot',    
'Flow IAT Std',    
'Pkt Size Avg',    
'Pkt Len Std',   
'Bwd Seg Size Avg',
'Fwd Act Data Pkts',    
'Pkt Len Var',  
'Idle Min',    
'Subflow Fwd Byts',    
'PSH Flag Cnt',    
'Fwd IAT Max',    
'Pkt Len Mean',   
'Idle Std',    
'Active Std',    
'Bwd IAT Mean',    
'Bwd IAT Max',    
'Fwd IAT Std',    
'Fwd IAT Mean',    
'Bwd IAT Std',    
'FIN Flag Cnt',    
'Fwd Header Len',
'Active Max',    
'Active Min',    
'Active Mean',   
'Idle Mean',   
'ACK Flag Cnt' ]]
y=dataset['Label']
# split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split( x,y,test_size=0.3)

# create the classifier object
clf = DecisionTreeClassifier()

# fit the classifier to the training data
clf.fit(X_train, y_train)

# get the feature importances
importances = clf.feature_importances_

# create a dataframe to store the feature importances
feature_importances = pd.DataFrame({'feature': X_train.columns, 'importance': importances})
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# sort the features by importance in descending order
feature_importances = feature_importances.sort_values('importance', ascending=False)

# print the feature importances
print(feature_importances)


# make predictions on the test data
y_pred = clf.predict(X_test)

# calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)

# print the accuracy of the classifier
print("Accuracy:", accuracy)


              feature  importance
0        RST Flag Cnt    0.424525
10         Bwd Pkts/s    0.050996
3   Init Bwd Win Byts    0.050654
11        Pkt Len Min    0.049924
1         Pkt Len Max    0.041056
2        Flow IAT Min    0.025207
13        Fwd IAT Min    0.024173
20  Fwd Act Data Pkts    0.023780
9         Bwd IAT Tot    0.023648
7          Fwd Pkts/s    0.021076
27           Idle Std    0.020293
5         Bwd IAT Min    0.020289
8       Flow IAT Mean    0.016680
25        Fwd IAT Max    0.015268
19   Bwd Seg Size Avg    0.012939
4        Flow IAT Max    0.011712
6    Subflow Bwd Byts    0.010966
36         Active Max    0.010269
23   Subflow Fwd Byts    0.010089
16       Flow IAT Std    0.009870
17       Pkt Size Avg    0.009781
37         Active Min    0.009567
14     Bwd Header Len    0.008823
22           Idle Min    0.008510
30        Bwd IAT Max    0.007857
15        Fwd IAT Tot    0.007704
24       PSH Flag Cnt    0.007571
31        Fwd IAT Std    0.007541
26       Pkt L

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    DOS ICMP       0.96      0.85      0.90       762
    DOS SYN        1.00      1.00      1.00      5035
    DOS UDP        0.97      1.00      0.98      4798
      Normal       0.98      0.97      0.98      6109

    accuracy                           0.98     16704
   macro avg       0.98      0.95      0.96     16704
weighted avg       0.98      0.98      0.98     16704



In [25]:
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion matrix:")
print(confusion_mat)

Confusion matrix:
[[ 646    1   23   92]
 [   0 5023    4    8]
 [   0    0 4780   18]
 [  24    6  129 5950]]


In [26]:
# perform 5-fold cross-validation and calculate the mean accuracy
scores = cross_val_score(clf, x, y, cv=5)
mean_accuracy = scores.mean()

# print the mean accuracy
print("Mean accuracy:", mean_accuracy)

Mean accuracy: 0.9860272988505747


In [27]:
class_counts = dataset['Label'].value_counts()
class_counts

Normal      20254
DOS SYN     16971
DOS UDP     15950
DOS ICMP     2505
Name: Label, dtype: int64